module.exports = (sequelize, DataTypes) =>{
    // Define the Comments model
    const Comments = sequelize.define("Comments",{
        // Define commentBody column
        commentBody: {
            // Set Data type to string
            type: DataTypes.STRING,
            // Set it as a required field
            allowNull: false,
        },
        username: {
            type: DataTypes.STRING,
            allowNull: false,
        }
        // When establishing a one-to-many relationship with Posts, a foreign key is generated by the Posts table
        // `PostId` int(11) DEFAULT NULL,
        // CONSTRAINT `Comments_ibfk_1` FOREIGN KEY (`PostId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE  
    });

    // Return the Comments model
    return Comments;
};