module.exports = (sequelize, DataTypes) =>{
    // Define the Likes model
    const Likes = sequelize.define("Likes");
    
    // When establishing a one-to-many relationship with Posts, a foreign key is generated by the Posts table
    // When establishing a one-to-many relationship with Users, a foreign key is generated by the Users table

    // `PostId` int(11) DEFAULT NULL,
    // `UserId` int(11) DEFAULT NULL,

    // CONSTRAINT `Likes_ibfk_1` FOREIGN KEY (`PostId`) REFERENCES `Posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    // CONSTRAINT `Likes_ibfk_2` FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
    
    // Return the Likes model
    return Likes;
};